package faker

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
var letterRunesAndNumbers = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")

var firstMaleNames = [...]string{"James", "Robert", "John", "Michael", "David", "William", "Richard",
	"Joseph", "Thomas", "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald",
	"Steven", "Paul", "Andrew", "Joshua", "Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald",
	"Edward", "Jason", "Jeffrey", "Ryan", "Jacob", "Aleksandr", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen",
	"Larry", "Justin", "Scott", "Brandon", "Benjamin", "Samuel", "Gregory", "Alexander", "Frank", "Mason",
	"Patrick", "Raymond", "Jack", "Dennis", "Jerry", "Tyler", "Aaron", "Jose", "Adam", "Nathan", "Philip",
	"Henry", "Douglas", "Zachary", "Peter", "Kyle", "Ethan", "Walter", "Noah", "Jeremy", "Christian",
	"Keith", "Roger", "Terry", "Gerald", "Harold", "Sean", "Austin", "Carl", "Arthur", "Lawrence", "Bobby",
	"Dylan", "Jesse", "Jordan", "Bryan", "Billy", "Joe", "Bruce", "Gabriel", "Logan", "Albert", "Louis",
	"Willie", "Alan", "Juan", "Wayne", "Elijah", "Randy", "Roy", "Vincent", "Ralph", "Eugene", "Russell"}

var firstFemaleNames = [...]string{"Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan",
	"Jessica", "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Margaret", "Sandra", "Ashley", "Kimberly",
	"Emily", "Donna", "Michelle", "Carol", "Amanda", "Dorothy", "Melissa", "Deborah", "Stephanie", "Rebecca",
	"Sharon", "Laura", "Cynthia", "Kathleen", "Amy", "Angela", "Shirley", "Anna", "Brenda", "Pamela", "Emma",
	"Nicole", "Helen", "Samantha", "Katherine", "Christine", "Debra", "Rachel", "Carolyn", "Janet", "Catherine",
	"Maria", "Heather", "Diane", "Ruth", "Julie", "Olivia", "Joyce", "Virginia", "Victoria", "Kelly", "Lauren",
	"Christina", "Joan", "Evelyn", "Judith", "Megan", "Andrea", "Cheryl", "Hannah", "Jacqueline", "Martha",
	"Gloria", "Teresa", "Ann", "Sara", "Madison", "Frances", "Kathryn", "Janice", "Jean", "Abigail", "Alice",
	"Julia", "Judy", "Sophia", "Grace", "Denise", "Amber", "Doris", "Marilyn", "Danielle", "Beverly", "Isabella",
	"Theresa", "Diana", "Natalie", "Brittany", "Charlotte", "Marie", "Kayla", "Alexis", "Lori"}

var lastNames = [...]string{"Smith",
	"Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez",
	"Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee",
	"Perez", "Thompson", "White", "Kireeva", "Harris", "Sanchez", "Kalinkin", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
	"Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams",
	"Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts"}

var langCodes = [...]string{"ab", "aa", "af", "ak", "sq", "am", "ar", "an", "hy", "as", "av", "ae", "ay", "az", "bm",
	"ba", "eu", "be", "bn", "bh", "bi", "bs", "br", "bg", "my", "ca", "ch", "ce", "ny", "zh", "cv", "yo", "za", "zu",
	"kw", "co", "cr", "hr", "cs", "da", "dv", "nl", "dz", "en", "eo", "et", "ee", "fo", "fj", "fi", "fr", "ff", "gl",
	"gd", "gv", "ka", "de", "el", "kl", "gn", "gu", "ht", "ha", "he", "hz", "hi", "ho", "hu", "is", "io", "ig", "in",
	"ia", "ie", "iu", "ik", "ga", "it", "ja", "jv", "kl", "kn", "kr", "ks", "kk", "km", "ki", "rw", "rn", "ky", "kv",
	"kg", "ko", "ku", "kj", "lo", "la", "lv", "li", "ln", "lt", "lu", "lg", "lb", "gv", "mk", "mg", "ms", "ml", "mt",
	"mi", "mr", "mh", "mo", "mn", "na", "nv", "ng", "nd", "ne", "no", "nb", "nn", "ii", "oc", "oj", "cu", "or", "om",
	"os", "pi", "ps", "fa", "pl", "pt", "pa", "qu", "rm", "ro", "ru", "se", "sm", "sg", "sa", "sr", "sh", "st", "tn",
	"sn", "ii", "sd", "si", "ss", "sk", "sl", "so", "nr", "es", "su", "sw", "ss", "sv", "tl", "ty", "tg", "ta", "tt",
	"te", "th", "bo", "ti", "to", "ts", "tr", "tk", "tw", "ug", "uk", "ur", "uz", "ve", "vi", "vo", "wa", "cy", "wo",
	"fy", "xh", "ji"}

var countries = [...]string{"Afghanistan", "Akrotiri", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
	"Anguilla", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahrain",
	"Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia And Herzegovina",
	"Botswana", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso",
	"Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
	"Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo (Brazzaville)",
	"Congo (Kinshasa)", "Cook Islands", "Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Curaçao ", "Cyprus",
	"Czechia", "Denmark", "Dhekelia", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
	"Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Islas Malvinas)", "Faroe Islands",
	"Federated States of Micronesia", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
	"French Southern And Antarctic Lands", "Gabon", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
	"Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana",
	"Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle Of Man",
	"Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
	"Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
	"Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
	"Mauritania", "Mauritius", "Mayotte", "Mexico", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
	"Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua",
	"Niger", "Nigeria", "Niue", "Norfolk Island", "North Korea", "Northern Mariana Islands", "Norway", "Oman", "Pakistan",
	"Palau", "Panama", "Papua New Guinea", "Paracel Islands", "Paraguay", "Peru", "Philippines", "Pitcairn Islands",
	"Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russia", "Rwanda", "Saint Barthelemy",
	"Saint Helena, Ascension, And Tristan Da Cunha", "Saint Kitts And Nevis", "Saint Lucia", "Saint Martin",
	"Saint Pierre And Miquelon", "Saint Vincent And The Grenadines", "Samoa", "San Marino", "Sao Tome And Principe",
	"Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia",
	"Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia And South Sandwich Islands", "South Korea",
	"South Sudan", "Spain", "Spratly Islands", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden",
	"Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "The Bahamas", "The Gambia", "Timor-Leste",
	"Togo", "Tokelau", "Tonga", "Trinidad And Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks And Caicos Islands",
	"Tuvalu", "U.S. Virgin Islands", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
	"Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis And Futuna", "West Bank",
	"Yemen", "Zambia", "Zimbabwe"}

var cities = [...]string{"Tokyo", "Jakarta", "Delhi", "Manila", "São Paulo", "Seoul", "Mumbai", "Shanghai", "Mexico City",
	"Guangzhou", "Cairo", "Beijing", "New York", "Kolkāta", "Moscow", "Bangkok", "Dhaka", "Buenos Aires", "Ōsaka",
	"Lagos", "Istanbul", "Karachi", "Kinshasa", "Shenzhen", "Bangalore", "Ho Chi Minh City", "Tehran", "Los Angeles",
	"Rio de Janeiro", "Chengdu", "Baoding", "Chennai", "Lahore", "London", "Paris", "Tianjin", "Linyi", "Shijiazhuang",
	"Zhengzhou", "Nanyang", "Hyderābād", "Wuhan", "Handan", "Nagoya", "Weifang", "Lima", "Zhoukou", "Luanda", "Ganzhou",
	"Tongshan", "Kuala Lumpur", "Chicago", "Heze", "Chongqing", "Hanoi", "Fuyang", "Changsha", "Dongguan", "Jining",
	"Jinan", "Pune", "Foshan", "Bogotá", "Ahmedabad", "Nanjing", "Changchun", "Tangshan", "Cangzhou", "Dar es Salaam",
	"Hefei", "Hong Kong", "Shaoyang", "Zhanjiang", "Shangqiu", "Nantong", "Yancheng", "Nanning", "Hengyang", "Zhumadian",
	"Shenyang", "Xingtai", "Xi’an", "Santiago", "Yantai", "Riyadh", "Luoyang", "Kunming", "Shangrao", "Hangzhou", "Bijie",
	"Quanzhou", "Miami", "Wuxi", "Huanggang", "Maoming", "Nanchong", "Zunyi", "Qujing", "Baghdad", "Xinyang", "Jieyang",
	"Khartoum", "Madrid", "Allahābād", "Yulin", "Changde", "Liaocheng", "Qingdao", "Dallas", "Nangandao", "Xiangyang",
	"Philadelphia", "Giza", "Lu’an", "Zhaotong", "Yichun", "Dezhou", "Nairobi", "Nanchang", "Tai’an", "Dazhou", "Houston",
	"Guadalajara", "Yongzhou", "Atlanta", "Novokuybishevsk", "Rangoon", "Toronto", "Suihua", "Saint Petersburg", "Washington",
	"Qiqihar", "Suzhou", "Shantou", "Weinan", "Changzhou", "Singapore", "Fuzhou", "Pudong", "Belo Horizonte", "Zhangzhou",
	"Yuncheng", "Suzhou", "Xianyang", "Guilin", "Taizhou", "Abidjan", "Huaihua", "Ji’an", "Xiaoganzhan", "Pingdingshan",
	"Jiujiang", "Sūrat", "Guiyang", "Alexandria", "Bozhou", "Sydney", "Huizhou", "Huai’an", "Chenzhou", "Barcelona",
	"Anqing", "Suqian", "Boston", "Jiangmen", "Mianyang", "Harbin", "Samara", "Huanglongsi", "Melbourne", "Zibo", "Dalian",
	"Hengshui", "Yibin", "Yangzhou", "Timbío", "Johannesburg", "Yiyang", "Guigang", "Xinpu", "Meizhou", "Casablanca",
	"Langfang", "Zhangjiakou", "Chifeng", "Linfen", "Jiangguanchi", "Kabul", "Phoenix", "Luzhou", "Taiyuan", "Zhaoqing",
	"Xiaoxita", "Xiamen", "Fuzhou", "Liuzhou", "Zhuzhou", "Amman", "Jeddah", "Chuzhou", "Loudi", "Deyang", "Qingyuan",
	"Kano", "Wuhu", "Seattle", "Yokohama", "Binzhou", "Baojishi", "Zaozhuang", "Neijiang", "Baicheng", "Berlin", "Anshan",
	"Lanzhou", "Puyang", "San Francisco", "Jiaozuo", "Hechi", "Montréal", "Detroit", "Chengde", "Busan", "Algiers",
	"Hanzhong", "Shiyan", "Lucknow", "Siping", "Yulinshi", "Changzhi", "Qinzhou", "Bazhou", "Qincheng", "Zhongshan",
	"Suining", "Leshan", "San Diego", "Faisalabad", "Guang’an", "Tongren", "Bengbu", "Santa Cruz", "Qinhuangdao",
	"Tongliao", "Jinzhou", "Zhenjiang", "Ürümqi", "Heyuan", "Jaipur", "Xinzhou", "Wuzhou"}

var domains = []string{"google.com", "facebook.com", "doubleclick.net", "google-analytics.com", "akamaihd.net",
	"googlesyndication.com", "googleapis.com", "googleadservices.com", "facebook.net", "youtube.com", "twitter.com",
	"scorecardresearch.com", "microsoft.com", "ytimg.com", "googleusercontent.com", "apple.com", "msftncsi.com",
	"2mdn.net", "googletagservices.com", "adnxs.com", "yahoo.com", "serving-sys.com", "akadns.net", "bluekai.com",
	"ggpht.com", "rubiconproject.com", "verisign.com", "addthis.com", "crashlytics.com", "amazonaws.com", "quantserve.com",
	"akamaiedge.net", "live.com", "googletagmanager.com", "revsci.net", "adadvisor.net", "openx.net", "digicert.com",
	"pubmatic.com", "agkn.com", "instagram.com", "mathtag.com", "gmail.com", "rlcdn.com", "linkedin.com", "yahooapis.com",
	"chartbeat.net", "twimg.com", "turn.com", "crwdcntrl.net", "demdex.net", "betrad.com", "flurry.com", "newrelic.com",
	"yimg.com", "youtube-nocookie.com", "exelator.com", "acxiom-online.com", "imrworldwide.com", "amazon.com",
	"fbcdn.net", "windowsupdate.com", "mookie1.com", "rfihub.com", "omniroot.com", "adsrvr.org", "nexac.com", "bing.com",
	"skype.com", "godaddy.com", "sitescout.com", "tubemogul.com", "contextweb.com", "w55c.net", "chartbeat.com",
	"akamai.net", "jquery.com", "adap.tv", "criteo.com", "krxd.net", "optimizely.com", "macromedia.com", "comodoca.com",
	"casalemedia.com", "pinterest.com", "adsymptotic.com", "symcd.com", "atwola.com", "adobe.com", "msn.com", "adsafeprotected.com",
	"tapad.com", "truste.com", "symantecliveupdate.com", "atdmt.com", "t.co", "avast.com", "google.co.in", "spotxchange.com",
	"tidaltv.com", "adtechus.com", "everesttech.net", "addthisedge.com", "hola.org", "btrll.com", "gwallet.com",
	"liverail.com", "windows.com", "burstnet.com", "disqus.com", "nr-data.net", "p-td.com", "geotrust.com", "admob.com",
	"crittercism.com", "bizographics.com", "ru4.com", "wtp101.com", "ksmobile.com", "msads.net", "thawte.com",
	"lijit.com", "cloudflare.com", "360yield.com", "dropbox.com", "simpli.fi", "smartadserver.com", "globalsign.com",
	"mlnadvertising.com", "chango.com", "connexity.net", "moatads.com", "s-msn.com", "entrust.net", "tribalfusion.com",
	"domdex.com", "google.com.tr", "whatsapp.net", "ntp.org", "amazon-adsystem.com", "viber.com", "disquscdn.com",
	"yandex.ru", "doubleverify.com", "bkrtx.com", "criteo.net", "outbrain.com", "questionmarket.com", "adform.net",
	"yieldmanager.com", "typekit.net", "goo.gl", "voicefive.com", "owneriq.net", "media6degrees.com", "tynt.com",
	"symcb.com", "advertising.com", "audienceiq.com", "wp.com", "rtbidder.net", "wikipedia.org", "adroll.com",
	"icloud.com", "gravatar.com", "collective-media.net", "appsflyer.com", "dmtry.com", "blogger.com", "taboola.com",
	"legolas-media.com", "images-amazon.com", "afy11.net", "aspnetcdn.com", "hike.in", "feedburner.com", "bootstrapcdn.com",
	"usertrust.com", "adgrx.com", "brilig.com", "sharethis.com", "flashtalking.com", "mediaplex.com", "eqads.com",
	"adscale.de", "imgur.com", "edgesuite.net", "blogspot.com", "msocsp.com", "wikimedia.org", "ssl-images-amazon.com",
	"amung.us", "flickr.com", "rundsp.com", "trouter.io", "edgekey.net", "rfihub.net", "utorrent.com", "thebrighttag.com",
	"eyeviewads.com", "kalink.in"}
